"""empty message

Revision ID: 12e708789094
Revises: 04929c222405
Create Date: 2024-02-04 23:54:24.865272

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '12e708789094'
down_revision = '04929c222405'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=345), nullable=True))
        batch_op.create_unique_constraint("unique_email", ['email'])
        batch_op.create_unique_constraint("unique_id", ['id'])
        batch_op.drop_constraint("unique_email", type_='unique')
        batch_op.drop_constraint("unique_id", type_='unique')
        batch_op.drop_column('user_id')
        batch_op.drop_column('friend_id')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friend_id', sa.VARCHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=32), nullable=False))
        batch_op.create_foreign_key(None, 'friends', ['friend_id'], ['id'])
        batch_op.create_foreign_key(None, 'friends', ['user_id'], ['id'])
        batch_op.create_unique_constraint("unique_email", ['email'])
        batch_op.create_unique_constraint("unique_id", ['id'])
        batch_op.drop_constraint("unique_email", type_='unique')
        batch_op.drop_constraint("unique_id", type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
